"use client";

import { Separator } from "@core/ui/separator";
import { CheckCircle2 } from "lucide-react";
import { useI18n } from "@core/providers/i18n-provider";
import type { EditionForConversion } from "../../../domain/interfaces/ILeadsRepository";
import type { PlatformLead } from "../../../domain/entities/PlatformLead";
import type { Step2State } from "../../viewmodels/useConvertWizardViewModel";

// ── Props ─────────────────────────────────────────────────────────────────────

interface WizardStep4Props {
  lead: PlatformLead | null;
  edition: EditionForConversion | null;
  setup: Step2State;
  overrideCount: number;
}

// ── Component ─────────────────────────────────────────────────────────────────

/**
 * React presentation component representing the wizard step4 confirm UI element.
 */
export function WizardStep4Confirm({ lead, edition, setup, overrideCount }: WizardStep4Props) {
  const { t, language } = useI18n();

  // Resolve localized subscription type display string
  const resolvedSubtypeLabel =
    setup.subscriptionType === "Monthly"
      ? t("leads.convertDialog.subscriptionMonthly")
      : setup.subscriptionType === "Yearly"
        ? t("leads.convertDialog.subscriptionYearly")
        : setup.subscriptionType === "Lifetime"
          ? t("leads.convertDialog.subscriptionLifetime")
          : t("leads.convertWizard.editionDefault");

  const rows: { label: string; value: string }[] = [
    { label: t("leads.createDialog.company"), value: lead?.companyName ?? "—" },
    { label: t("leads.columns.contact"), value: lead?.contactName ?? "—" },
    {
      label: t("leads.convertWizard.confirmStep.adminEmail"),
      value: setup.adminEmail || lead?.email || "—",
    },
    {
      label: t("leads.convertWizard.confirmStep.edition"),
      value:
        (language === "ar" && edition?.displayNameAr
          ? edition.displayNameAr
          : edition?.displayNameEn) ?? "—",
    },
    {
      label: t("leads.convertWizard.confirmStep.tenantSlug"),
      value: setup.tenantCode || t("leads.convertWizard.confirmStep.autoGenerated"),
    },
    {
      label: t("leads.convertWizard.confirmStep.billing"),
      value: `${resolvedSubtypeLabel} · ${setup.currency}`,
    },
    ...(setup.useCustomPrice
      ? [
          {
            label: t("leads.convertWizard.confirmStep.dealPrice"),
            value: `${Number(setup.negotiatedAmount).toLocaleString()} ${setup.negotiatedCurrency}`,
          },
        ]
      : []),
    ...(overrideCount > 0
      ? [
          {
            label: t("leads.convertWizard.confirmStep.featureOverrides"),
            value: t("leads.convertWizard.featureCustomized", { count: overrideCount }),
          },
        ]
      : []),
  ];

  return (
    <div className="space-y-4">
      <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-5 py-4 dark:border-emerald-900 dark:bg-emerald-950/30">
        <div className="flex items-center gap-3">
          <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600 dark:text-emerald-400" />
          <div>
            <p className="text-sm font-semibold text-emerald-800 dark:text-emerald-300">
              {t("leads.convertWizard.readyToConvert", { defaultValue: "Ready to convert" })}
            </p>
            <p className="mt-0.5 text-xs text-emerald-700 dark:text-emerald-400">
              {t("leads.convertWizard.step4Desc")}
            </p>
          </div>
        </div>
      </div>

      <div className="overflow-hidden rounded-xl border border-border">
        {rows.map((row, i) => (
          <div key={row.label}>
            {i > 0 && <Separator />}
            <div className="flex items-center justify-between px-4 py-2.5">
              <span className="text-xs text-muted-foreground">{row.label}</span>
              <span className="text-sm font-medium text-foreground">{row.value}</span>
            </div>
          </div>
        ))}
      </div>

      {setup.conversionNote && (
        <div className="rounded-xl border border-border px-4 py-3">
          <p className="mb-1 text-xs font-medium text-muted-foreground">
            {t("leads.convertWizard.internalNote")}
          </p>
          <p className="text-sm text-foreground">{setup.conversionNote}</p>
        </div>
      )}
    </div>
  );
}
