/**
 * Settings Defaults
 *
 * Default values for all 61 settings. Single source of truth.
 */

import type { Settings } from "./types";

export const defaultSettings: Settings = {
  colorTheme: "blue",
  lightBackgroundTheme: "default",
  darkBackgroundTheme: "slate",
  shadowIntensity: "subtle",
  secondaryColorTheme: "slate",
  gradientDirection: "to-br",
  lightGradientTheme: "none",
  darkGradientTheme: "none",
  customPrimaryColor: "#3b82f6",
  customSecondaryColor: "#64748b",
  customLightBgColor: "#ffffff",
  customDarkBgColor: "#0f172a",
  activePalette: "corporate-classic",
  backgroundMode: "preset",
  gradientStartColor: "#3b82f6",
  gradientEndColor: "#8b5cf6",
  layoutTemplate: "navigation",
  cardStyle: "default",
  animationLevel: "moderate",
  fontSize: "default",
  showDetailPanel: true,
  borderRadius: "default",
  sidebarPosition: "left",
  headerStyle: "default",
  sidebarStyle: "default",
  buttonStyle: "default",
  navigationStyle: "sidebar",
  spacingSize: "default",
  iconStyle: "outline",
  inputStyle: "default",
  tableStyle: "default",
  badgeStyle: "outlined",
  avatarStyle: "default",
  logoType: "image",
  logoAnimation: "none",
  logoSize: "xl",
  logoText: "",
  showBreadcrumbs: true,
  showUserAvatar: true,
  showNotifications: true,
  compactMode: false,
  highContrast: false,
  reducedMotion: false,
  stickyHeader: true,
  collapsibleSidebar: true,
  showFooter: true,
  autoSave: true,
  showLogo: true,
  formStyle: "default",
  loadingStyle: "ripple",
  tooltipStyle: "default",
  modalStyle: "default",
  treeStyle: "lines",
  datePickerStyle: "default",
  calendarStyle: "default",
  selectStyle: "default",
  switchStyle: "default",
  checkboxStyle: "default",
  radioStyle: "default",
  toastStyle: "classic",
  showToastIcons: true,
  toastDuration: 5000,
  hoverEffectType: "none",
  hoverEffectIntensity: "none",
};

/** All setting keys — derived from defaultSettings for runtime iteration */
export const SETTINGS_KEYS = Object.keys(defaultSettings) as (keyof Settings)[];
