/**
 * Constant definition representing en.
 */
export const en = {
  modules: {
    revenueAnalytics: {
      title: "Revenue Analytics Engine",
      description:
        "BI-grade revenue intelligence with 7-tab dashboard, real-time KPIs, cohort analysis, LTV modeling, revenue forecasting, tenant health scoring, and automated PDF report delivery.",
      intro:
        "The Revenue Analytics Engine provides comprehensive financial intelligence for your SaaS platform. It aggregates subscription data from all tenants into actionable KPIs, trend visualizations, and predictive models. Nightly background jobs snapshot all metrics, compute tenant health scores, and generate scheduled reports — delivering a complete BI-grade analytics suite without external tools.",
      kpiTitle: "KPI Overview",
      kpiIntro:
        "Eight core KPIs are calculated in real-time from subscription and payment data. Each KPI supports date range filtering, period-over-period comparison, and drill-down by edition or tenant.",
      tabsTitle: "7-Tab Dashboard",
      tabsIntro:
        "The analytics dashboard is organized into 7 lazy-loaded tabs, each focusing on a specific analytical dimension. Tabs are rendered via React.lazy with Suspense fallbacks for optimal bundle splitting.",
      snapshotTitle: "AnalyticsSnapshot Entity",
      snapshotIntro:
        "The AnalyticsSnapshot entity stores daily metric snapshots. Each night, the AnalyticsSnapshotJob creates one aggregate row (TenantId = null) and one row per active tenant. This enables historical trend analysis without querying live subscription tables.",
      healthTitle: "Tenant Health Scoring",
      healthIntro:
        "The TenantHealthScoreJob computes a composite health score (0–100) for each active tenant using a weighted formula that combines payment reliability, platform activity, and subscription growth signals.",
      jobsTitle: "Background Jobs Pipeline",
      jobsIntro:
        "Three background jobs run in strict sequence every night. They are fully provider-agnostic — configurable to run under Native, Hangfire, or Quartz via appsettings.json. Each job implements IAutoRegisteredJob for unified management.",
      jobsConfig:
        "All three jobs are configurable via appsettings.json under BackgroundJobs:Jobs. You can override the CRON schedule, enable/disable individual jobs, or switch providers (Native/Hangfire/Quartz) without code changes.",
      endpointsTitle: "API Endpoints",
      endpointsIntro:
        "The AnalyticsController exposes 12 endpoints under /api/v1/analytics. All endpoints require SuperAdmin role and the corresponding analytics permission.",
      exportTitle: "Export System",
      exportIntro:
        "Analytics data can be exported in three formats. Each export includes the current KPI summary, MRR trends, and subscription breakdown. PDF exports include branded headers and charts.",
      scheduledTitle: "Scheduled Reports",
      scheduledIntro:
        "Administrators can configure automated report delivery. Reports are generated by the AnalyticsReportJob at 6:00 AM UTC and emailed to the configured recipients in the chosen format.",
      permissionsTitle: "Permissions",
      permissionsIntro:
        "Revenue Analytics uses four granular permissions that can be assigned to roles via the standard RBAC system.",
      ep: {
        summary: "Get analytics summary (KPI cards + period comparison)",
        mrr: "Get MRR waterfall movements (new/expansion/contraction/churn/reactivation)",
        cohort: "Get cohort retention heatmap data by monthly cohorts",
        ltv: "Get lifetime value breakdown by edition tier",
        forecast: "Get 6-month revenue forecast with linear regression + confidence bands",
        health: "Get tenant health scores with risk classification",
        snapshots: "Get historical daily snapshots for trend charts",
        export: "Export analytics data in specified format (csv/excel/pdf)",
        reportList: "List all scheduled reports",
        reportCreate: "Create a new scheduled report configuration",
        reportUpdate: "Update scheduled report settings",
        reportDelete: "Delete a scheduled report",
      },
    },
  },
};
