export const en = {
  modules: {
    revenueAnalytics: {
      description:
        "BI-grade revenue intelligence with 7-tab dashboard, real-time KPIs, cohort analysis, LTV modeling, revenue forecasting, tenant health scoring, and automated PDF report delivery.",
      endpointsIntro:
        "The AnalyticsController exposes 12 endpoints under /api/v1/analytics. All endpoints require SuperAdmin role and the corresponding analytics permission.",
      endpointsTitle: "API Endpoints",
      ep: {
        cohort: "Get cohort retention heatmap data by monthly cohorts",
        export: "Export analytics data in specified format (csv/excel/pdf)",
        forecast: "Get 6-month revenue forecast with linear regression + confidence bands",
        health: "Get tenant health scores with risk classification",
        ltv: "Get lifetime value breakdown by edition tier",
        mrr: "Get MRR waterfall movements (new/expansion/contraction/churn/reactivation)",
        reportCreate: "Create a new scheduled report configuration",
        reportDelete: "Delete a scheduled report",
        reportList: "List all scheduled reports",
        reportUpdate: "Update scheduled report settings",
        snapshots: "Get historical daily snapshots for trend charts",
        summary: "Get analytics summary (KPI cards + period comparison)",
      },
      exportIntro:
        "Analytics data can be exported in three formats. Each export includes the current KPI summary, MRR trends, and subscription breakdown. PDF exports include branded headers and charts.",
      exportTitle: "Export System",
      healthIntro:
        "The TenantHealthScoreJob computes a composite health score (0–100) for each active tenant using a weighted formula that combines payment reliability, platform activity, and subscription growth signals.",
      healthTitle: "Tenant Health Scoring",
      intro:
        "The Revenue Analytics Engine provides comprehensive financial intelligence for your SaaS platform. It aggregates subscription data from all tenants into actionable KPIs, trend visualizations, and predictive models. Nightly background jobs snapshot all metrics, compute tenant health scores, and generate scheduled reports — delivering a complete BI-grade analytics suite without external tools.",
      jobsConfig:
        "All three jobs are configurable via appsettings.json under BackgroundJobs:Jobs. You can override the CRON schedule, enable/disable individual jobs, or switch providers (Native/Hangfire/Quartz) without code changes.",
      jobsIntro:
        "Three background jobs run in strict sequence every night. They are fully provider-agnostic — configurable to run under Native, Hangfire, or Quartz via appsettings.json. Each job implements IAutoRegisteredJob for unified management.",
      jobsTitle: "Background Jobs Pipeline",
      kpiIntro:
        "Eight core KPIs are calculated in real-time from subscription and payment data. Each KPI supports date range filtering, period-over-period comparison, and drill-down by edition or tenant.",
      kpiTitle: "KPI Overview",
      permissionsIntro:
        "Revenue Analytics uses four granular permissions that can be assigned to roles via the standard RBAC system.",
      permissionsTitle: "Permissions",
      scheduledIntro:
        "Administrators can configure automated report delivery. Reports are generated by the AnalyticsReportJob at 6:00 AM UTC and emailed to the configured recipients in the chosen format.",
      scheduledTitle: "Scheduled Reports",
      snapshotIntro:
        "The AnalyticsSnapshot entity stores daily metric snapshots. Each night, the AnalyticsSnapshotJob creates one aggregate row (TenantId = null) and one row per active tenant. This enables historical trend analysis without querying live subscription tables.",
      snapshotTitle: "AnalyticsSnapshot Entity",
      tabsIntro:
        "The analytics dashboard is organized into 7 lazy-loaded tabs, each focusing on a specific analytical dimension. Tabs are rendered via React.lazy with Suspense fallbacks for optimal bundle splitting.",
      tabsTitle: "7-Tab Dashboard",
      title: "Revenue Analytics Engine",
    },
  },
};
