"use client";

import { Separator } from "@core/ui/separator";
import { DetailRow } from "@core/ui/detail-row";
import { CheckCircle2 } from "lucide-react";
import { useI18n } from "@core/providers/i18n-provider";
import type { EditionForConversion } from "../../../domain/interfaces/ILeadsRepository";
import type { PlatformLead } from "../../../domain/entities/PlatformLead";
import type { Step2State } from "../../viewmodels/useConvertWizardViewModel";

// ── Props ─────────────────────────────────────────────────────────────────────

interface WizardStep4Props {
  lead: PlatformLead | null;
  edition: EditionForConversion | null;
  setup: Step2State;
  overrideCount: number;
}

// ── Component ─────────────────────────────────────────────────────────────────

/**
 * Presentation UI component rendering the wizard step4 confirm.
 * Arranges layout boundaries and accessibility targets (WCAG, tab index) using the core design library (@core/ui/*). Coordinates text fields, submit indicators, and validation warning messages.
 */
export function WizardStep4Confirm({ lead, edition, setup, overrideCount }: WizardStep4Props) {
  const { t, language } = useI18n();

  // Resolve localized subscription type display string
  const resolvedSubtypeLabel =
    setup.subscriptionType === "Monthly"
      ? t("leads.convertDialog.subscriptionMonthly")
      : setup.subscriptionType === "Yearly"
        ? t("leads.convertDialog.subscriptionYearly")
        : setup.subscriptionType === "Lifetime"
          ? t("leads.convertDialog.subscriptionLifetime")
          : t("leads.convertWizard.editionDefault");

  const rows: { label: string; value: string }[] = [
    { label: t("leads.createDialog.company"), value: lead?.companyName ?? "—" },
    { label: t("leads.columns.contact"), value: lead?.contactName ?? "—" },
    {
      label: t("leads.convertWizard.confirmStep.adminEmail"),
      value: setup.adminEmail || lead?.email || "—",
    },
    {
      label: t("leads.convertWizard.confirmStep.edition"),
      value:
        (language === "ar" && edition?.displayNameAr
          ? edition.displayNameAr
          : edition?.displayNameEn) ?? "—",
    },
    {
      label: t("leads.convertWizard.confirmStep.tenantSlug"),
      value: setup.tenantCode || t("leads.convertWizard.confirmStep.autoGenerated"),
    },
    {
      label: t("leads.convertWizard.confirmStep.billing"),
      value: `${resolvedSubtypeLabel} · ${setup.currency}`,
    },
    ...(setup.useCustomPrice
      ? [
          {
            label: t("leads.convertWizard.confirmStep.dealPrice"),
            value: `${Number(setup.negotiatedAmount).toLocaleString()} ${setup.negotiatedCurrency}`,
          },
        ]
      : []),
    ...(overrideCount > 0
      ? [
          {
            label: t("leads.convertWizard.confirmStep.featureOverrides"),
            value: t("leads.convertWizard.featureCustomized", { count: overrideCount }),
          },
        ]
      : []),
  ];

  return (
    <div className="space-y-4">
      <div className="rounded-nx-md border border-success/30 bg-success/10 px-5 py-4">
        <div className="flex items-center gap-3">
          <CheckCircle2 className="h-5 w-5 shrink-0 text-success" aria-hidden="true" />
          <div>
            <p className="text-sm font-semibold text-success">
              {t("leads.convertWizard.readyToConvert", { defaultValue: "Ready to convert" })}
            </p>
            <p className="mt-0.5 text-xs text-success">{t("leads.convertWizard.step4Desc")}</p>
          </div>
        </div>
      </div>

      <div className="overflow-hidden rounded-nx-lg border border-nx-line">
        {rows.map((row, i) => (
          <div key={row.label}>
            {i > 0 && <Separator />}
            <div className="px-4 py-2.5">
              <DetailRow label={row.label} value={row.value} />
            </div>
          </div>
        ))}
      </div>

      {setup.conversionNote && (
        <div className="rounded-nx-md border border-nx-line px-4 py-3">
          <p className="mb-1 text-xs font-medium text-nx-ink-3">
            {t("leads.convertWizard.internalNote")}
          </p>
          <p className="text-sm text-nx-ink">{setup.conversionNote}</p>
        </div>
      )}
    </div>
  );
}
