import type { TenantOverviewData } from "./tenantTypes";

export type TenantMockData = TenantOverviewData;

export const TENANT_MOCK_DATA: TenantOverviewData = {
  tenantName: "Cairo Sports Club",
  location: "Cairo, Egypt",
  planName: "Professional Plan",
  readinessPercent: 84,
  setupStepsCompleted: 4,
  setupStepsTotal: 5,
  metaPills: [
    { label: "3 Branches", icon: "🏢" },
    { label: "12 Admins", icon: "👥" },
    { label: "428 Athletes", icon: "⚽" },
    { label: "Active since Jan 2024", icon: "🗓" },
  ],
  readinessChecks: [
    { label: "Core configuration healthy", status: "success" },
    { label: "2 products active", status: "success" },
    { label: "2 admin invitations pending", status: "warning" },
  ],
  kpis: {
    setupCompletion: {
      value: 84,
      sub: "1 essential step remaining",
      trend: "↑ 8%",
    },
    adminsAndUsers: {
      value: 12,
      sub: "2 invitations pending",
      trend: "↑ 20%",
    },
    branchesAndSites: {
      current: 3,
      total: 5,
      percent: 60,
      sub: "60% of plan capacity",
      trend: "+1",
    },
    enabledProducts: {
      active: 2,
      total: 3,
      sub: "Venue and Academy active",
      trend: "Explore",
    },
  },
  steps: [
    {
      id: 1,
      title: "Organization Profile",
      description: "Basic information and workspace identity.",
      status: "done",
    },
    {
      id: 2,
      title: "Add Branches / Sites",
      description: "3 active sites configured.",
      status: "done",
    },
    {
      id: 3,
      title: "Invite Your Team",
      description: "12 admins, 2 pending invitations.",
      status: "done",
    },
    {
      id: 4,
      title: "Configure Integrations",
      description: "Connect communication and business tools.",
      status: "current",
      actionLabel: "Set Up",
      href: "/integrations",
    },
    {
      id: 5,
      title: "Customize Workspace",
      description: "Branding, menus and preferences.",
      status: "upcoming",
      actionLabel: "Customize",
      href: "/settings",
    },
  ],
  products: [
    {
      id: "venue",
      name: "SCRIPE Venue",
      description: "Manage facilities, bookings and daily venue operations.",
      status: "active",
      stats: [
        { label: "Sites", value: "3" },
        { label: "Resources", value: "14" },
        { label: "Bookings", value: "2.4K" },
      ],
      buttonLabel: "Open Venue →",
      href: "/venues",
    },
    {
      id: "academy",
      name: "SCRIPE Academy",
      description: "Manage athletes, programs, groups and development.",
      status: "active",
      stats: [
        { label: "Athletes", value: "428" },
        { label: "Groups", value: "19" },
        { label: "Coaches", value: "12" },
      ],
      buttonLabel: "Open Academy →",
      href: "/academy",
    },
    {
      id: "football-intelligence",
      name: "Football Intelligence",
      description: "AI-powered scouting, analysis and performance insights.",
      status: "inactive",
      stats: [
        { label: "Player analysis", value: "—" },
        { label: "Match analysis", value: "—" },
      ],
      buttonLabel: "Explore Product →",
      href: "/football-intelligence",
    },
  ],
  quotas: [
    {
      id: "staff",
      label: "Staff Members",
      current: "84",
      total: "100",
      percent: 84,
      subLeft: "84% used",
      subRight: "16 left",
      color: "green",
    },
    {
      id: "sites",
      label: "Sites / Branches",
      current: "3",
      total: "5",
      percent: 60,
      subLeft: "60% used",
      subRight: "2 left",
      color: "blue",
    },
    {
      id: "storage",
      label: "Storage",
      current: "62 GB",
      total: "100 GB",
      percent: 62,
      subLeft: "62% used",
      subRight: "38 GB left",
      color: "violet",
    },
    {
      id: "api",
      label: "API Requests",
      current: "12K",
      total: "50K",
      percent: 24,
      subLeft: "24% used",
      subRight: "This month",
      color: "amber",
    },
  ],
  alerts: [
    {
      id: "alt-1",
      title: "Finish branch configuration",
      description: "Main Branch is missing contact information",
      severity: "warning",
      href: "/branches",
    },
    {
      id: "alt-2",
      title: "2 staff invitations expired",
      description: "Resend invitations to activate accounts",
      severity: "critical",
      href: "/admins",
    },
    {
      id: "alt-3",
      title: "Payment method requires update",
      description: "Your card expires in 5 days",
      severity: "warning",
      href: "/settings",
    },
    {
      id: "alt-4",
      title: "WhatsApp integration disconnected",
      description: "Reconnect to enable notifications",
      severity: "critical",
      href: "/integrations",
    },
  ],
  quickActions: [
    {
      id: "qa-1",
      title: "Invite Admin",
      description: "Add a team member",
      icon: "👤",
      color: "#12b981",
      href: "/admins",
    },
    {
      id: "qa-2",
      title: "Create Branch",
      description: "Add a new site",
      icon: "🏢",
      color: "#2b83ff",
      href: "/branches",
    },
    {
      id: "qa-3",
      title: "Manage Roles",
      description: "Set permissions",
      icon: "👥",
      color: "#ef4c5a",
      href: "/roles",
    },
    {
      id: "qa-4",
      title: "Workspace Settings",
      description: "Branding & preferences",
      icon: "⚙",
      color: "#8a56f5",
      href: "/settings",
    },
  ],
  activityFeed: [
    {
      id: "act-1",
      author: "Ahmed Hassan",
      avatarText: "AH",
      action: "Created a new staff member",
      timeAgo: "2m",
    },
    {
      id: "act-2",
      author: "Sara Mohamed",
      avatarText: "SM",
      avatarColor: "#0b8b68",
      action: "Updated academy group U14",
      timeAgo: "12m",
    },
    {
      id: "act-3",
      author: "System",
      avatarText: "SYS",
      avatarColor: "#7b42d1",
      action: "Branch “New Cairo” activated",
      timeAgo: "1h",
    },
    {
      id: "act-4",
      author: "Omar Khaled",
      avatarText: "OK",
      action: "Changed booking policy",
      timeAgo: "3h",
    },
  ],
  systemNotices: [
    {
      id: "not-1",
      title: "All SCRIPE services are operational",
      description: "Last checked 5 minutes ago",
      timeAgo: "Now",
      isSuccess: true,
    },
    {
      id: "not-2",
      title: "New feature: Custom Fields",
      description: "Create custom fields for members and staff.",
      timeAgo: "3d",
      isSuccess: false,
    },
  ],
};
