/**
 * planPickerTypes — Interface specifications and viewmodel contracts for plan and tier selection.
 */

import type { PlanEdition, ComparisonCategory } from "../../domain/entities";
import type { OnboardingRecommendation } from "../../domain/entities/OnboardingEntities";
import { CURRENCY_TO_COUNTRY } from "../helpers/currencyGeo";

/**
 * Resolves appropriate BCP-47 locale string for regional currency and number formatting.
 *
 * @param language Active UI language code.
 * @param currency Target ISO-4217 currency code.
 * @returns BCP-47 locale identifier string.
 */
export function resolveLocale(language: string, currency: string): string {
  if (language === "ar") return "ar";
  const country = CURRENCY_TO_COUNTRY[currency?.toUpperCase()];
  return country ? `en-${country}` : "en-US";
}

/**
 * Hand-set native currencies with pre-configured exchange baselines.
 * Currencies outside this set are FX-converted from USD.
 */
export const SEEDED_CURRENCIES = new Set(["USD", "EUR", "SAR", "EGP"]);

/**
 * A plan edition enriched with recommendation matching metadata.
 */
export interface PlanPickerEdition extends PlanEdition {
  /** True when this edition matches the server recommendation (encrypted-id compare). */
  isRecommended: boolean;
}

/**
 * Contract defining the state and action handlers returned by the plan picker hook.
 */
export interface PlanPickerViewModel {
  /** Asynchronous catalog query state */
  isLoading: boolean;
  /** Query failure error indicator */
  isError: boolean;
  /** Catalog reload retry trigger */
  retry: () => void;

  /** Active industry or vertical slug */
  activeIndustry: string | null;
  /** Switch active vertical category */
  setIndustry: (slug: string) => void;
  /** List of available vertical industry categories */
  industries: { slug: string; label: string }[];

  /** Active ISO-4217 currency code */
  currency: string;
  /** BCP-47 locale identifier */
  locale: string;
  /** Geo-detected two-letter ISO country code */
  detectedCountry: string | null;
  /** Flag indicating whether prices are FX-converted from USD */
  isFxConverted: boolean;

  /** Selected billing frequency */
  billingCycle: "monthly" | "annual";
  /** Change billing cycle frequency */
  setBillingCycle: (cycle: "monthly" | "annual") => void;
  /** Computed annual billing savings percentage */
  annualSavingsPercent: number;
  /** Whether the active vertical offers paid subscription tiers */
  hasPaidEditions: boolean;

  /** Ordered list of plan editions */
  editions: PlanPickerEdition[];
  /** Categorized comparison matrix rows */
  comparisonCategories: ComparisonCategory[];
  /** Discovery answer priority keys for visual highlighting */
  priorityKeys: string[];
}

/**
 * Arguments required to initialize the plan picker viewmodel.
 */
export interface UsePlanPickerArgs {
  /** Selected business industry vertical */
  businessType: string | null;
  /** Answers provided during initial onboarding discovery */
  discoveryAnswers: Record<string, string[]>;
  /** Recommendation payload generated by the platform */
  recommendation: OnboardingRecommendation | undefined;
  /** Initial fallback currency code */
  initialCurrency?: string;
  /** Initial fallback country code */
  initialCountry?: string | null;
}
