/**
 * CreateTenantStep2 — Administrator Setup
 *
 * Collects: admin email, username.
 * Includes the secure onboarding info callout.
 *
 * @module tenants/presentation/components
 */
"use client";

import React from "react";
import { Input } from "@core/ui/input";
import { Label } from "@core/ui/label";
import { UserPlus, Mail, Shield } from "lucide-react";
import type { CreateTenantVM } from "../../viewmodels/useCreateTenantViewModel";

interface CreateTenantStep2Props {
  vm: CreateTenantVM;
  t: (key: string) => string;
}

/**
 * Presentation UI component rendering the create tenant step2.
 * Arranges layout boundaries and accessibility targets (WCAG, tab index) using the core design library (@core/ui/*). Coordinates text fields, submit indicators, and validation warning messages.
 */
export function CreateTenantStep2({ vm, t }: CreateTenantStep2Props) {
  const touched = vm.stepTouched[2];
  const errors = vm.stepErrors[2];
  const emailEmpty = touched && errors.includes("adminEmail");
  const emailFormatError = errors.includes("adminEmailFormat");
  const emailError = emailEmpty || emailFormatError;

  return (
    <div className="space-y-6">
      <div className="mb-2 flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-nx-md bg-info/10">
          <UserPlus className="h-5 w-5 text-info" />
        </div>
        <div>
          <h2 className="text-lg font-semibold">
            {t("tenant.stepAdministrator")}
          </h2>
          <p className="text-sm text-nx-ink-2">
            {t("tenant.stepAdministratorDesc")}
          </p>
        </div>
      </div>

      {/* Info callout */}
      <div className="flex items-start gap-3 rounded-nx-md border border-info/20 bg-info/5 p-4">
        <Shield className="mt-0.5 h-5 w-5 shrink-0 text-info" />
        <div className="text-sm text-nx-ink-2">
          <p className="mb-1 font-medium text-nx-ink">
            {t("tenant.secureOnboarding")}
          </p>
          {t("tenant.secureOnboardingDesc")}
        </div>
      </div>

      <div className="grid gap-5 sm:grid-cols-2">
        <div className="space-y-2">
          <Label htmlFor="admin-email">
            {t("tenant.adminEmail")} <span className="text-destructive">*</span>
          </Label>
          <div className="relative" dir="ltr">
            <Mail
              className="absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-nx-ink-2"
              aria-hidden="true"
            />
            <Input
              id="admin-email"
              type="email"
              value={vm.form.adminEmail}
              onChange={(e) => vm.updateField("adminEmail", e.target.value)}
              placeholder="admin@example.com"
              className="ps-10"
              aria-invalid={emailError || undefined}
              aria-describedby={emailError ? "tenant-admin-email-error" : undefined}
              dir="ltr"
              autoFocus
            />
          </div>
          {emailEmpty && (
            <p id="tenant-admin-email-error" className="text-xs text-destructive">
              {t("validation.invalidAdminEmail")}
            </p>
          )}
          {emailFormatError && (
            <p className="text-xs text-destructive">
              {t("validation.invalidEmail")}
            </p>
          )}
        </div>

        <div className="space-y-2">
          <Label htmlFor="admin-username">
            {t("tenant.adminUsername")}
          </Label>
          <Input
            id="admin-username"
            value={vm.form.adminUsername}
            onChange={(e) => vm.updateField("adminUsername", e.target.value)}
            placeholder={t("tenant.autoGenerated")}
            className="font-mono"
            dir="ltr"
          />
          <p className="text-xs text-nx-ink-2">
            {t("tenant.usernameHint")}
          </p>
        </div>
      </div>
    </div>
  );
}
