export const en = {
  definitionExport: {
    // The header action that opens the dialog, and the dialog's own title. "Definitions" is in both
    // because the neighbouring schema export is also called "export", and the two produce very
    // different files.
    openLabel: "Export definitions",
    title: "Export custom-field definitions",
    description:
      "Download a spreadsheet of your custom-field definitions — what fields exist, of what type, with what configuration. It contains no stored values.",

    // The scope picker.
    entityType: "Entity Type",
    entityTypePlaceholder: "All entity types",
    allEntityTypes: "All entity types",
    entityTypeHint:
      "Pick one entity type to export just its fields, or leave this on all entity types for the full list.",

    contents:
      "One row per definition, with its labels, value type, options, validator, sensitivity and scope. Fields you don't have access to are left out.",

    // The 'Included in exports' column is REPORTED, never used as a filter -- so this says plainly
    // that a field with the setting off still appears. An admin auditing their configuration would
    // otherwise assume rows were missing.
    exportableNote:
      "The 'Included in exports' column shows each field's setting. It doesn't decide which rows appear — every definition you can see is listed, including ones with that setting off.",

    exportAction: "Export",
    exporting: "Exporting…",

    // Shown after a successful download, so the file can be recognised in a downloads folder. The
    // name is generated by this app, not read from the response -- see buildDefinitionExportFileName.
    result: "Downloaded {fileName} ({size}).",

    // The row-cap REFUSAL. Not a failure: the server refused rather than truncating, because a
    // spreadsheet that stops at row 10,000 reads as a complete answer. Names the cap and the remedy.
    refused: {
      title: "Export refused — too many definitions",
      description:
        "This scope holds more than {max} definitions, and the export was refused rather than cut short at {max} rows. Choose a single entity type above and export again.",
    },

    // The payload was not a workbook. Something between this app and the API answered instead of the
    // export, and saving it would produce a file a spreadsheet refuses to open.
    unexpectedFile: {
      title: "That wasn't a spreadsheet",
      description:
        "The server's reply wasn't an Excel file, so nothing was saved. Sign in again and retry; if it keeps happening, the request isn't reaching the export.",
    },

    // The stream was taken by a download manager, which means the file WAS saved -- just not by this
    // app, so there is no name or size to report.
    intercepted: {
      title: "Handed to your download manager",
      description:
        "Your download manager captured the file, so it isn't listed here. Check its downloads for a file starting with 'custom-field-definitions'.",
    },

    loadFailed: "Couldn't load the entity types.",

    toast: {
      exported: "Definitions exported.",
      exportFailed: "Couldn't export the definitions.",
      intercepted: "Your download manager captured the export.",
      unexpectedFile: "The server's reply wasn't a spreadsheet, so nothing was saved.",
    },
  },
};
