export const en = {
  valueExport: {
    // The header action that opens the dialog, and the dialog's own title. "Values" is in both
    // because the neighbouring definitions/schema exports are also called "export", and this is the
    // one that carries somebody's actual recorded data.
    openLabel: "Export values",
    title: "Export custom-field values",
    description:
      "Download a spreadsheet of the stored custom-field values recorded against one entity type's records — one row per record and field. It contains no field configuration.",

    // The scope picker. Mandatory here, unlike the definitions export: there is no "all entity
    // types" option, because a values export walks real records for one type at a time.
    entityType: "Entity Type",
    entityTypePlaceholder: "Choose an entity type",
    entityTypeHint:
      "Only entity types whose records you're permitted to view are listed. Exporting checks that permission again on the server, for the entity type you pick.",

    contents:
      "One row per record and field, with the field's label, value type and sensitivity, and the record's own stored value as plain text. Fields you don't have access to are left out.",

    exportAction: "Export",
    exporting: "Exporting…",

    // Shown after a successful download, so the file can be recognised in a downloads folder. The
    // name is generated by this app, not read from the response.
    result: "Downloaded {fileName} ({size}).",

    // The handler's cell-count REFUSAL (records x visible fields). Not a failure: the server
    // refused rather than truncating, because a spreadsheet that stops partway reads as a complete
    // answer. Unlike the definitions export there is no narrower scope to switch to from this
    // dialog -- the entity type is already the whole scope -- so the remedy names what actually
    // shrinks the count.
    refused: {
      title: "Export refused — too many values",
      description:
        "This entity type has more than {max} record-and-field combinations, and the export was refused rather than cut short. It can only be exported once there are fewer records, or fewer custom fields, on this entity type.",
    },

    // The caller picked an entity type they cannot view records for. The filtered picker makes this
    // unreachable on a fresh permission set; reaching it at all means a cached permission list
    // disagreed with a fresher server check.
    forbidden: {
      title: "You don't have view access to this entity type's records",
      description:
        "Your access changed since this list loaded. Close and reopen this dialog, or ask an administrator for view access to this entity type.",
    },

    // The payload was not a workbook.
    unexpectedFile: {
      title: "That wasn't a spreadsheet",
      description:
        "The server's reply wasn't an Excel file, so nothing was saved. Sign in again and retry; if it keeps happening, the request isn't reaching the export.",
    },

    // The stream was taken by a download manager, which means the file WAS saved.
    intercepted: {
      title: "Handed to your download manager",
      description:
        "Your download manager captured the file, so it isn't listed here. Check its downloads for a file starting with 'custom-field-values'.",
    },

    loadFailed: "Couldn't load the entity types.",

    // The real empty state: every entity type loaded, and none of them are ones this caller may
    // view records for. Worded for the person reading it, not as a generic placeholder -- and it
    // says what would change the answer, since "nothing to export" alone reads as a dead end.
    noViewableEntityTypes: {
      title: "Nothing here you can export yet",
      description:
        "You don't have view access to any entity type's records. Ask an administrator to grant view access to at least one, then reopen this dialog.",
    },

    toast: {
      exported: "Values exported.",
      exportFailed: "Couldn't export the values.",
      intercepted: "Your download manager captured the export.",
      unexpectedFile: "The server's reply wasn't a spreadsheet, so nothing was saved.",
    },
  },
};
