/**
 * CreateTenantStep2 — Administrator Setup
 *
 * Collects: admin email, username.
 * Includes the secure onboarding info callout.
 *
 * @module tenants/presentation/components
 */
"use client";

import React from "react";
import { cn } from "@core/common/utils";
import { Input } from "@core/ui/input";
import { Label } from "@core/ui/label";
import { UserPlus, Mail, Shield } from "lucide-react";
import type { CreateTenantVM } from "../../viewmodels/useCreateTenantViewModel";

interface CreateTenantStep2Props {
  vm: CreateTenantVM;
  t: (key: string) => string;
}

/**
 * Presentation UI component rendering the create tenant step2.
 * Arranges layout boundaries and accessibility targets (WCAG, tab index) using the core design library (@core/ui/*). Coordinates text fields, submit indicators, and validation warning messages.
 */
export function CreateTenantStep2({ vm, t }: CreateTenantStep2Props) {
  const touched = vm.stepTouched[2];
  const errors = vm.stepErrors[2];
  const emailEmpty = touched && errors.includes("adminEmail");
  const emailFormatError = errors.includes("adminEmailFormat");
  const emailError = emailEmpty || emailFormatError;

  return (
    <div className="space-y-6">
      <div className="mb-2 flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10">
          <UserPlus className="h-5 w-5 text-blue-500" />
        </div>
        <div>
          <h2 className="text-lg font-semibold">
            {t("tenant.stepAdministrator") || "Administrator"}
          </h2>
          <p className="text-sm text-muted-foreground">
            {t("tenant.stepAdministratorDesc") ||
              "Set up the initial admin account for this tenant."}
          </p>
        </div>
      </div>

      {/* Info callout */}
      <div className="flex items-start gap-3 rounded-xl border border-blue-500/20 bg-blue-500/5 p-4">
        <Shield className="mt-0.5 h-5 w-5 shrink-0 text-blue-500" />
        <div className="text-sm text-muted-foreground">
          <p className="mb-1 font-medium text-foreground">
            {t("tenant.secureOnboarding") || "Secure Onboarding"}
          </p>
          {t("tenant.secureOnboardingDesc") ||
            "The admin will receive a secure email with a one-time link to set their password. The account remains locked until they complete the setup."}
        </div>
      </div>

      <div className="grid gap-5 sm:grid-cols-2">
        <div className="space-y-2">
          <Label htmlFor="admin-email" className="text-sm font-medium">
            {t("tenant.adminEmail") || "Admin Email"} <span className="text-destructive">*</span>
          </Label>
          <div className="relative" dir="ltr">
            <Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              id="admin-email"
              type="email"
              value={vm.form.adminEmail}
              onChange={(e) => vm.updateField("adminEmail", e.target.value)}
              placeholder="admin@example.com"
              className={cn("h-11 pl-10 text-left", emailError && "border-destructive")}
              dir="ltr"
              autoFocus
            />
          </div>
          {emailEmpty && (
            <p className="text-xs text-destructive">
              {t("validation.invalidAdminEmail") || "Admin email is required."}
            </p>
          )}
          {emailFormatError && (
            <p className="text-xs text-destructive">
              {t("validation.invalidEmail") || "Please enter a valid email address."}
            </p>
          )}
        </div>

        <div className="space-y-2">
          <Label htmlFor="admin-username" className="text-sm font-medium">
            {t("tenant.adminUsername") || "Admin Username"}
          </Label>
          <Input
            id="admin-username"
            value={vm.form.adminUsername}
            onChange={(e) => vm.updateField("adminUsername", e.target.value)}
            placeholder={t("tenant.autoGenerated") || "Auto-generated from code"}
            className="h-11 text-left font-mono"
            dir="ltr"
          />
          <p className="text-xs text-muted-foreground">
            {t("tenant.usernameHint") || "Leave blank to auto-generate from tenant code."}
          </p>
        </div>
      </div>
    </div>
  );
}
